// Generated by CoffeeScript 1.6.2
(function() {
  $(document).ready(function() {
    var allColumnElements, cVal, cValNumberOfUses, checkIfColumnsLoaded, countOfDomChecks, followedBool, hideSideBar, initialize, keyCodes, numberOfColumnsToTrack, numberOfUses, numberWrappedAndPushed, percentScroll, previousScrollPosition, timeHTMLpersists, twttrLibraryLoaded, window_in_focus_bool;

    keyCodes = {
      'y': 121,
      'u': 117,
      'i': 105,
      'o': 111,
      'leftSquareBracket': 91
    };
    percentScroll = 1;
    numberOfColumnsToTrack = 6;
    allColumnElements = [];
    numberWrappedAndPushed = 0;
    previousScrollPosition = 0;
    followedBool = false;
    numberOfUses = 0;
    hideSideBar = false;
    cVal = jQuery.cookie('walkBackClickBool');
    cValNumberOfUses = jQuery.cookie('numberOfUses');
    if (cVal != null) {
      if (cVal === false || cVal === 'false') {
        followedBool = false;
      } else {
        followedBool = true;
      }
    } else {
      jQuery.cookie('walkBackClickBool', false, {
        expires: 1065
      });
    }
    if (cValNumberOfUses != null) {
      numberOfUses = parseInt(cValNumberOfUses);
      numberOfUses++;
      jQuery.cookie('numberOfUses', numberOfUses, {
        expires: 1065
      });
    } else {
      jQuery.cookie('numberOfUses', 1, {
        expires: 1065
      });
    }
    if (followedBool === true) {
      timeHTMLpersists = 3500;
    } else if (numberOfUses < 20) {
      timeHTMLpersists = 8500;
    } else {
      timeHTMLpersists = 11500;
    }
    window_in_focus_bool = true;
    countOfDomChecks = 0;
    twttrLibraryLoaded = false;
    checkIfColumnsLoaded = function() {
      allColumnElements = $(".column-scroller");
      if (countOfDomChecks > 7 && allColumnElements.length > 0 && typeof twttr !== 'undefined') {
        return twttr.ready(function(twttr_) {
          return initialize(twttr_);
        });
      } else if (allColumnElements.length > numberOfColumnsToTrack - 1 && typeof twttr !== 'undefined') {
        return twttr.ready(function(twttr_) {
          return initialize(twttr_);
        });
      } else {
        countOfDomChecks++;
        return setTimeout(function() {
          return checkIfColumnsLoaded();
        }, 2500);
      }
    };
    initialize = function(twttr_) {
      var currentScrollPositionFromTop, followHTML, tweetButtonHTML, verticalHeight, verticalHeightFull;

      verticalHeightFull = $(window).height();
      verticalHeight = parseInt(verticalHeightFull * .87);
      currentScrollPositionFromTop = 0;
      $($(".js-column-scroller")[0]).click();
      $(window).keypress(function(event) {
        var columnEl, _i, _j, _k, _l, _len, _len1, _len2, _len3, _results, _results1, _results2, _results3;

        if (event.charCode === keyCodes['y']) {
          currentScrollPositionFromTop = previousScrollPosition;
          previousScrollPosition = 0;
          _results = [];
          for (_i = 0, _len = allColumnElements.length; _i < _len; _i++) {
            columnEl = allColumnElements[_i];
            _results.push($(columnEl).scrollTop(currentScrollPositionFromTop));
          }
          return _results;
        } else if (event.charCode === keyCodes['u']) {
          previousScrollPosition = currentScrollPositionFromTop;
          currentScrollPositionFromTop -= verticalHeight;
          _results1 = [];
          for (_j = 0, _len1 = allColumnElements.length; _j < _len1; _j++) {
            columnEl = allColumnElements[_j];
            _results1.push($(columnEl).scrollTop(currentScrollPositionFromTop));
          }
          return _results1;
        } else if (event.charCode === keyCodes['i']) {
          previousScrollPosition = currentScrollPositionFromTop;
          currentScrollPositionFromTop += verticalHeight;
          if (verticalHeight > currentScrollPositionFromTop) {
            currentScrollPositionFromTop = 0;
          }
          _results2 = [];
          for (_k = 0, _len2 = allColumnElements.length; _k < _len2; _k++) {
            columnEl = allColumnElements[_k];
            _results2.push($(columnEl).scrollTop(currentScrollPositionFromTop));
          }
          return _results2;
        } else if (event.charCode === keyCodes['o']) {
          currentScrollPositionFromTop = 0;
          _results3 = [];
          for (_l = 0, _len3 = allColumnElements.length; _l < _len3; _l++) {
            columnEl = allColumnElements[_l];
            _results3.push($(columnEl).scrollTop(currentScrollPositionFromTop));
          }
          return _results3;
        } else if (event.charCode === keyCodes['leftSquareBracket']) {
          if (hideSideBar === false) {
            $(".js-app-content").css('left', '0');
            $(".js-app-header").css('z-index', -300);
            return hideSideBar = true;
          } else {
            $(".js-app-content").css('left', '40px');
            $(".js-app-header").css('z-index', 100);
            return hideSideBar = false;
          }
        }
      });
      tweetButtonHTML = "<br>      <div id='listenForFollowClickWalkback' style='padding-top:5px;'><a href='https://twitter.com/spencenow' class='twitter-follow-button' data-show-count='false' data-dnt='true'>Follow @spencenow</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></div>";
      if (followedBool === true || numberOfUses < 20) {
        tweetButtonHTML = '';
      }
      followHTML = "<div id='removeFollowButton' style='position: fixed; bottom: 50px; padding:5px; right:100px; opacity:0; z-index:100000;      border-color:darkgreen; border-style:solid; border-width:1px; background-color:white; text-align: center;'><span style='margin:10px;'> WalkBack's finished initializing. </span> &nbsp; <span id='closeFollowBox' style='padding-left:4px; padding-right:4px; border-color:grey; border-style: solid; border-width:1px; color: grey;' >&#10006;</span> " + tweetButtonHTML + "</div>";
      $(document.body).prepend(followHTML);
      return setTimeout(function() {
        return $("#removeFollowButton").animate({
          'opacity': 1
        }, {
          'duration': 1000,
          'complete': function() {
            $("#closeFollowBox").click(function() {
              return $("#removeFollowButton").remove();
            });
            twttr_.events.bind('click', function(event) {
              return jQuery.cookie('walkBackClickBool', true, {
                expires: 65
              });
            });
            return setTimeout(function() {
              return $("#removeFollowButton").animate({
                'opacity': 0
              }, {
                'duration': 2000,
                'complete': function() {
                  return $("#removeFollowButton").remove();
                }
              });
            }, timeHTMLpersists);
          }
        });
      }, 3000);
    };
    return checkIfColumnsLoaded();
  });

}).call(this);
